name: technical_test1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  connectivity_plus: ^3.0.4
  intl: ^0.18.0
  firebase_core: ^2.11.0
  cloud_firestore: ^4.6.0
  get: 4.6.5
  flutter_svg: 2.0.5
  google_fonts: 4.0.4
  firebase_auth: 4.6.1
  image_picker: 0.8.7+5
  firebase_storage: 11.2.2
  google_sign_in: 6.1.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/placeholder/dummy_600x400_ffffff_cccccc.png
    - assets/logo/courdev-big.svg
    - assets/logo/courdev-small.svg
    - assets/logo/google-icons.svg
    - assets/top-decoration.svg
    - assets/icon/icon-email.svg
    - assets/icon/icon-name.svg
    - assets/icon/icon-password.svg
    - assets/icon/icon-trash.svg
    - assets/icon/icon-arrow.svg
    - assets/Rate.svg
    - assets/add-product.svg
    - assets/icon/icon-logout.svg
  uses-material-design: true

