name: technical_test1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  connectivity_plus: ^3.0.4
  intl: ^0.18.0
  firebase_core: ^2.11.0
  cloud_firestore: ^4.6.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/placeholder/dummy_600x400_ffffff_cccccc.png
  uses-material-design: true

